version: 0.0
os: linux
files:
   - source: build/
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure_apache.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_apache.sh
      timeout: 300
      runas: root
